# Generated by Django 4.2.1 on 2023-05-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-last_login', 'id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
