# Generated by Django 4.2.1 on 2023-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
